# -*- coding: utf-8 -*-
"""依赖清单解析离线测试：夹具在运行时写入临时目录，零网络、零服务。

覆盖 v1.5.0 新增的 8 类清单（poetry.lock / yarn.lock / pubspec.* / mix.lock /
Podfile.lock / packages.lock.json / gradle.lockfile / Package.swift），
并验证所有生态产出**同一结构**的 Dep 记录（统一格式承诺的直接证据）。

运行：python manifesttest.py
"""
from __future__ import annotations

import os
import sys
import tempfile
import types

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from core import manifests  # noqa: E402

PASS = 0


def check(name, cond, extra=""):
    global PASS
    mark = "PASS" if cond else "FAIL"
    print(f"  {mark}  {name}" + (f"  — {extra}" if extra else ""))
    if cond:
        PASS += 1
    return cond


FIXTURES = {
    "poetry.lock": '''# generated by poetry
[[package]]
name = "requests"
version = "2.31.0"
category = "main"

[[package]]
name = "pytest"
version = "7.4.2"
category = "dev"

[metadata]
lock-version = "2.0"
''',
    "yarn.lock": '''# yarn lockfile v1
"@babel/code-frame@^7.0.0":
  version "7.22.13"
  resolved "https://registry.yarnpkg.com/@babel/code-frame/-/code-frame-7.22.13.tgz"

lodash@^4.17.20:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz"
''',
    "pubspec.lock": '''packages:
  args:
    dependency: "direct main"
    source: hosted
    version: "2.4.2"
  test_api:
    dependency: "transitive"
    source: hosted
    version: "0.7.3"
  build_runner:
    dependency: "direct dev"
    source: hosted
    version: "2.4.8"
''',
    "pubspec.yaml": '''name: demo
environment:
  sdk: ^3.2.0
dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  provider: ^6.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
''',
    "mix.lock": '''%{
"phoenix": {:hex, :phoenix, "1.7.10", "0ce1f7c5", [:mix], [{:castore, ">= 0.0.0", [hex: :castore]}], "hexpm"},
"plug": {:hex, :plug, "1.15.2", "94cf1fa4", [:mix], [], "hexpm"}
}
''',
    "Podfile.lock": '''PODS:
  - Alamofire (5.6.4)
  - Firebase/Core (10.18.0)

DEPENDENCIES:
  - Alamofire (~> 5.6)

SPEC REPOS:
  trunk:
    - Alamofire
''',
    "packages.lock.json": '''{
  "version": 1,
  "dependencies": {
    "net8.0": {
      "Newtonsoft.Json": {
        "type": "Direct",
        "requested": "[13.0.3, )",
        "resolved": "13.0.3"
      },
      "Newtonsoft.Json.Bson": {
        "type": "Transitive",
        "resolved": "1.0.2"
      }
    }
  }
}
''',
    "gradle.lockfile": '''# This is a Gradle generated file for dependency locking.
com.fasterxml.jackson.core:jackson-databind:2.15.2=compileClasspath,runtimeClasspath
junit:junit:4.13.2=testCompileClasspath,testRuntimeClasspath
''',
    "Package.swift": '''// swift-tools-version:5.9
let package = Package(
    dependencies: [
        .package(url: "https://github.com/apple/swift-argument-parser", from: "1.3.0"),
        .package(url: "https://github.com/apple/swift-log.git", exact: "1.5.3"),
        .package(url: "https://github.com/vapor/vapor", .upToNextMajor(from: "4.8.0")),
    ]
)
''',
}


class Entry:
    """模拟引擎的 FileEntry（只需 rel/abs）。"""

    def __init__(self, root, rel):
        self.rel = rel.replace("\\", "/")
        self.abs = os.path.join(root, rel)


def run():
    print("[manifesttest] 依赖清单解析离线测试\n")
    tmp = tempfile.mkdtemp(prefix="manfix-")
    for rel, content in FIXTURES.items():
        p = os.path.join(tmp, rel)
        os.makedirs(os.path.dirname(p), exist_ok=True)
        with open(p, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(content)

    entries = [Entry(tmp, rel) for rel in FIXTURES]
    deps, meta = manifests.parse(entries)

    by_eco = {}
    for d in deps:
        by_eco.setdefault(d["ecosystem"], []).append(d)

    print("[1] 各生态均被识别")
    for eco in ("pypi", "npm", "pub", "hex", "cocoapods", "nuget", "maven", "swift"):
        check(f"生态 {eco} 有记录", eco in by_eco,
              f"{len(by_eco.get(eco, []))} 条")

    print("\n[2] 版本与可信度")
    get = lambda eco, name: next((d for d in by_eco.get(eco, []) if d["name"] == name), None)  # noqa: E731
    check("poetry: requests 2.31.0 exact",
          (get("pypi", "requests") or {}).get("version") == "2.31.0"
          and get("pypi", "requests", ).get("version_kind") == "exact")
    check("poetry: pytest 标记 test 作用域",
          (get("pypi", "pytest") or {}).get("scope") == "test")
    check("yarn: scoped 包名解析正确",
          (get("npm", "@babel/code-frame") or {}).get("version") == "7.22.13")
    check("yarn: lodash 4.17.21",
          (get("npm", "lodash") or {}).get("version") == "4.17.21")
    check("pubspec.lock: direct main / transitive / direct dev 三态",
          (get("pub", "args") or {}).get("indirect") is False
          and (get("pub", "test_api") or {}).get("indirect") is True
          and (get("pub", "build_runner") or {}).get("scope") == "test")
    check("pubspec.yaml: ^1.1.0 取下界且标 floor",
          (get("pub", "http") or {}).get("version") == "1.1.0"
          and (get("pub", "http") or {}).get("version_kind") == "floor")
    check("pubspec.yaml: sdk 依赖不产出记录", get("pub", "flutter") is None)
    check("mix.lock: phoenix 1.7.10",
          (get("hex", "phoenix") or {}).get("version") == "1.7.10")
    check("Podfile.lock: 子规格归并主包",
          (get("cocoapods", "Firebase") or {}).get("version") == "10.18.0")
    check("nuget lock: Direct/Transitive 区分",
          (get("nuget", "Newtonsoft.Json") or {}).get("indirect") is False
          and (get("nuget", "Newtonsoft.Json.Bson") or {}).get("indirect") is True)
    check("gradle.lockfile: group:artifact 命名与 test 作用域",
          (get("maven", "junit:junit") or {}).get("scope") == "test"
          and (get("maven", "com.fasterxml.jackson.core:jackson-databind") or {})
          .get("version") == "2.15.2")
    check("Package.swift: from 取下界 floor",
          (get("swift", "https://github.com/apple/swift-argument-parser") or {})
          .get("version_kind") == "floor")
    check("Package.swift: exact 精确锁定",
          (get("swift", "https://github.com/apple/swift-log.git") or {})
          .get("version_kind") == "exact")

    print("\n[3] 统一格式（Dep 记录结构一致性）")
    required = {"ecosystem", "name", "version", "raw", "version_kind",
                "version_note", "manifest", "module", "scope", "indirect", "coord"}
    bad = [d for d in deps if not required.issubset(d.keys())]
    check(f"全部 {len(deps)} 条记录字段结构一致", not bad)
    check("OSV 生态映射齐备",
          all(d["ecosystem"] in manifests.OSV_ECOSYSTEM for d in deps),
          ", ".join(sorted({d["ecosystem"] for d in deps})))
    check("清单来源可追溯（manifest 字段非空）", all(d["manifest"] for d in deps))

    print(f"\n{'=' * 60}")
    print(f"  结果：{PASS} 项通过，全部通过 ✓" if PASS >= 24 else
          f"  结果：{PASS} 项通过（存在失败项，见上方 FAIL）")
    print(f"{'=' * 60}")
    return 0 if PASS >= 24 else 1


if __name__ == "__main__":
    sys.exit(run())
